### ISSUE TITLE
xsbt-web webapp reloading instructions

### ISSUE THREAD

**Issue by alejo90** [Gekkio/sbt-jrebel-plugin#3]
Hi, according to readme, `jrebel.webLinks <++= webappSrc in webapp` should be used to enable webapp resource reloading. I tried it and it fails on sbt 0.13.5 because `jrebel.webLinks` is a settings key and `webappSrc` is a task key. According to [sbt docs](http://www.scala-sbt.org/0.13.5/docs/Getting-Started/More-About-Settings.html#tasks-with-dependencies):

> a setting key can't depend on a task key

What worked for me is: 

```
jrebel.webLinks += (target in Compile).value / "webapp"
```

**Comment by kflorence** [comment]
See here for most up to date information on running JRebel with xsbt-web: https://github.com/earldouglas/xsbt-web-plugin/blob/master/docs/2.1.md
